---
- name: Stop EC2 instance
  hosts: all
  become: true
  gather_facts: yes

  tasks:
   # - name: Debug ansible_facts  
   #   ansible.builtin.debug:
   #     var: ansible_facts

    - name: Shutting down ubuntu instances only
      ansible.builtin.command: /sbin/shutdown -t now
      when: ansible_facts['os_family'] == "Debian"

  