---
- hosts: localhost
  connection: local
  vars:
    ansible_python_interpreter: "/home/pavgav/playbooks/venv/bin/python" 

  tasks:
    - name: Create EC2 instances
      amazon.aws.ec2_instance:
        name: "{{ item.name}}"
        key_name: "test118"
        #vpc_subnet_id: subnet-5ca1ab1e
        instance_type: t2.micro
        security_group: default
        region: ap-south-1
        aws_access_key: "{{ec2_access_key}}"  # From vault as defined
        aws_secret_key: "{{ec2_secret_key}}"  # From vault as defined
        network: 
          assign_public_ip: true
        image_id: "{{ item.image }}"
        tags:
          environment: "{{item.name}}"
      loop:
        - { image: "ami-0fd05997b4dff7aac", name: "manage-node-1" } 
        - { image: "ami-053b12d3152c0cc71", name: "manage-node-2" } 
        - { image: "ami-053b12d3152c0cc71", name: "manage-node-3" } 

